### ISSUE TITLE
UnhandledPromiseRejectionWarning Error

### ISSUE THREAD

**Issue by bwalshin** [tushardhadiwal/homebridge-levoitcore-client#3]
I have the Levoit Core400S and the Core200S which made me really like the idea of this plugin as the original doesn't support newer models. When trying to load it, I receive the error below. 

Is this a known issue? What would be the best way to fix this?

```
(node:31860) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mode' of null
    at new VesyncFan (/usr/local/lib/node_modules/homebridge-levoitcore-client/dist/fan/vesyncFan.js:7:42)
    at /usr/local/lib/node_modules/homebridge-levoitcore-client/dist/api/client.js:113:37
    at Array.map (<anonymous>)
    at VesyncClient.getDevices (/usr/local/lib/node_modules/homebridge-levoitcore-client/dist/api/client.js:113:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at VesyncPlatform.findDevices (/usr/local/lib/node_modules/homebridge-levoitcore-client/dist/index.js:165:22)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-levoitcore-client/dist/index.js:161:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TristanBrotherton** [comment]
I am having the same issue, and unable to use the plugin as it currently stands
